from docx import Document

from docx.shared import (
    Inches,
    Pt
)

from docx.enum.text import (
    WD_ALIGN_PARAGRAPH
)

from app.logging.trace_logger import (
    log_trace
)


# ---------------------------------------------------
# HELPERS
# ---------------------------------------------------

def add_page_break(doc):

    doc.add_page_break()


def add_centered_title(
    doc,
    text,
    size=28
):

    p = doc.add_paragraph()

    p.alignment = (
        WD_ALIGN_PARAGRAPH.CENTER
    )

    run = p.add_run(text)

    run.bold = True

    run.font.size = Pt(size)

    run.font.name = (
        "Times New Roman"
    )


def add_heading(
    doc,
    text
):

    heading = doc.add_paragraph()

    heading.paragraph_format.space_before = Pt(18)

    heading.paragraph_format.space_after = Pt(10)

    run = heading.add_run(text)

    run.bold = True

    run.font.size = Pt(20)

    run.font.name = (
        "Times New Roman"
    )


def add_body_paragraph(
    doc,
    text
):

    p = doc.add_paragraph()

    p.paragraph_format.line_spacing = 1.5

    p.paragraph_format.space_after = Pt(12)

    p.paragraph_format.first_line_indent = (
        Inches(0.2)
    )

    run = p.add_run(text)

    run.font.size = Pt(12)

    run.font.name = (
        "Times New Roman"
    )


# ---------------------------------------------------
# MAIN ASSEMBLER
# ---------------------------------------------------

def run_assembler(state):

    try:

        outline = state["outline"]

        chapters = state["chapters"]

        glossary = state.get(
            "glossary",
            []
        )

        references = state.get(
            "references",
            []
        )

        title = outline.get(
            "book_title",
            "Untitled Book"
        )

        doc = Document()

        # ---------------------------------------------------
        # PAGE SETUP
        # ---------------------------------------------------

        section = doc.sections[0]

        section.top_margin = Inches(1)

        section.bottom_margin = Inches(1)

        section.left_margin = Inches(1)

        section.right_margin = Inches(1)

        # ---------------------------------------------------
        # TITLE PAGE
        # ---------------------------------------------------

        doc.add_paragraph("\n")
        doc.add_paragraph("\n")
        doc.add_paragraph("\n")

        add_centered_title(
            doc,
            title,
            size=30
        )

        subtitle = doc.add_paragraph()

        subtitle.alignment = (
            WD_ALIGN_PARAGRAPH.CENTER
        )

        run = subtitle.add_run(
            "Generated by AIuthor"
        )

        run.italic = True

        run.font.size = Pt(14)

        run.font.name = (
            "Times New Roman"
        )

        add_page_break(doc)

        # ---------------------------------------------------
        # COPYRIGHT
        # ---------------------------------------------------

        add_heading(
            doc,
            "Copyright"
        )

        add_body_paragraph(
            doc,
            "ISBN: 000-0-00-000000-0"
        )

        add_body_paragraph(
            doc,
            "First Edition"
        )

        add_body_paragraph(
            doc,
            "All rights reserved."
        )

        add_page_break(doc)

        # ---------------------------------------------------
        # TABLE OF CONTENTS
        # ---------------------------------------------------

        add_heading(
            doc,
            "Table of Contents"
        )

        for chapter in chapters:

            toc = doc.add_paragraph()

            toc.paragraph_format.space_after = Pt(2)

            run = toc.add_run(

                f"Chapter "
                f"{chapter['chapter_number']}: "
                f"{chapter['title']}"
            )

            run.font.size = Pt(12)

            run.font.name = (
                "Times New Roman"
            )

        add_page_break(doc)

        # ---------------------------------------------------
        # INTRODUCTION
        # ---------------------------------------------------

        add_heading(
            doc,
            "Introduction"
        )

        add_body_paragraph(

            doc,

            f"This book explores "
            f"{state['user_brief']['topic']} "
            f"through a "
            f"{state['user_brief']['tone']} "
            f"lens, helping readers engage "
            f"with the topic in an emotionally "
            f"engaging and thoughtful way."
        )

        add_page_break(doc)

        # ---------------------------------------------------
        # CHAPTERS
        # ---------------------------------------------------

        for idx, chapter in enumerate(chapters):

            add_heading(

                doc,

                f"Chapter "
                f"{chapter['chapter_number']}: "
                f"{chapter['title']}"
            )

            paragraphs = chapter[
                "content"
            ].split("\n")

            for para in paragraphs:

                para = para.strip()

                if para:

                    add_body_paragraph(
                        doc,
                        para
                    )

            # ONLY between chapters

            if idx < len(chapters) - 1:

                add_page_break(doc)

        # ---------------------------------------------------
        # REFERENCES
        # ---------------------------------------------------

        if references:

            add_page_break(doc)

            add_heading(
                doc,
                "References"
            )

            for ref in references:

                add_body_paragraph(

                    doc,

                    f"• {ref}"
                )

        # ---------------------------------------------------
        # GLOSSARY
        # ---------------------------------------------------

        if glossary:

            add_page_break(doc)

            add_heading(
                doc,
                "Glossary"
            )

            for item in glossary:

                term = item.get(
                    "term",
                    ""
                )

                definition = item.get(
                    "definition",
                    ""
                )

                p = doc.add_paragraph()

                p.paragraph_format.space_after = Pt(8)

                bold = p.add_run(
                    f"{term}: "
                )

                bold.bold = True

                bold.font.name = (
                    "Times New Roman"
                )

                bold.font.size = Pt(12)

                normal = p.add_run(
                    definition
                )

                normal.font.name = (
                    "Times New Roman"
                )

                normal.font.size = Pt(12)

        # ---------------------------------------------------
        # AFTERWORD
        # ---------------------------------------------------

        add_heading(
            doc,
            "Afterword"
        )

        add_body_paragraph(

            doc,

            "Thank you for reading this "
            "book. May these ideas continue "
            "to inspire reflection, growth, "
            "and meaningful change."
        )

        # ---------------------------------------------------
        # ABOUT AUTHOR
        # ---------------------------------------------------

        add_heading(
            doc,
            "About the Author"
        )

        add_body_paragraph(

            doc,

            "AIuthor is an agentic AI-powered "
            "book generation system capable "
            "of planning, writing, humanizing, "
            "fact-checking, and assembling "
            "publication-style manuscripts."
        )

        # ---------------------------------------------------
        # SAVE
        # ---------------------------------------------------

        output_path = (
            "generated_book.docx"
        )

        doc.save(output_path)

        print(
            "DOCX SAVED"
        )

        log_trace(
            "assembler",
            "SUCCESS"
        )

        return {

            **state,

            "generated_docx":
                output_path
        }

    except Exception as e:

        log_trace(
            "assembler",
            "FAILED",
            str(e)
        )

        return {

            **state,

            "logs":
                state["logs"] + [
                    {
                        "agent":
                            "assembler",

                        "error":
                            str(e)
                    }
                ]
        }